5 2 4 inkwell
howker/surf-flutter-course-kudryashov pull request #20
Opened 2021-03-14 10:56 UTC by howker

![Screenshot_1615718661](https://user-images.githubusercontent.com/26591622/111065854-6148e600-84d5-11eb-8f9c-173033b93860.png)
![Screenshot_1615718812](https://user-images.githubusercontent.com/26591622/111065855-6312a980-84d5-11eb-831d-0080106a930b.png)

2021-03-15 19:08 UTC, artem-zaitsev requested changes
НЕобходимы правки по данному ПР.

2021-03-15 19:08 UTC, artem-zaitsev commented on lib/ui/widgets/sight_card.dart
> +              Positioned.fill(
Рипл залезает за края карточки, этого не должно быть.
По сути вам надо засунуть его под Clip.

Более того, есть ощущение, что он из-за fill карточка увеличилась в размерах.

Надо переделать.

2021-03-16 17:20 UTC, howker commented
Спасибо! 
![Screenshot_1615915139](https://user-images.githubusercontent.com/26591622/111352228-65bffb00-869d-11eb-99bb-c789e028ad79.png)
Исправил.

2021-03-17 15:43 UTC, artem-zaitsev approved these changes

2021-03-18 04:00 UTC, merged