4 3 2 layout list places
howker/surf-flutter-course-kudryashov pull request #9
Opened 2020-12-09 11:50 UTC by howker

![Screenshot_1607514117](https://user-images.githubusercontent.com/26591622/101626356-48dcb180-3a36-11eb-95c3-aef9bf195a7b.png)

2020-12-10 10:23 UTC, artem-zaitsev requested changes
Из предыдущего ПРа - коммент с неймингом переезжает и на этот.

Поправьте еще и замечания здесь. Приведите дизайн к тому, что в фигме.(текст в описании карточки, краткое описание)

2020-12-10 10:23 UTC, artem-zaitsev commented on lib/ui/screen/sight_card.dart
> +                    padding: EdgeInsets.only(
Расстояние между элементами лучше вставлять отдельными виджетами(например, SizedBox). Таким образом не будет лишней вложенности и будет более констистентно с дизайном.

2020-12-10 10:23 UTC, artem-zaitsev commented on lib/ui/screen/sight_card.dart
> +                      style: smallFontStyle,
Судя по скрину - что-то не так с текстовым стилем.
Выдерните из контейнера. Для начала.

2020-12-10 10:23 UTC, artem-zaitsev commented on lib/ui/screen/sight_card.dart
> +class SightCard extends StatelessWidget {
Для виджетов лучше писать доки. Просто описать что это за виджет(еще удобно прикрепить ссылку на дизайн)

2020-12-13 12:48 UTC, howker commented
Исправил

2020-12-14 09:43 UTC, artem-zaitsev approved these changes
Про доки написал в предыдщем ПРе.
Это не блочит, но перед слиянием учтите.

2020-12-14 10:50 UTC, merged